### ISSUE TITLE
US2-1: Database changes

### ISSUE THREAD

**Issue by luciafang** [CMU-313/nodebb-f24-team-kale#16]

**Comment by luciafang** [comment]
Description: Modify the database schema to support anonymous questions. Add a new boolean column (isAnonymous) to the questions table, which will indicate whether a question is posted anonymously.
Estimated Effort: 4 hours
Dependencies: None
Milestone: Sprint 2
Acceptance Criteria: The database schema is updated, and status data can be stored and retrieved correctly.

**Comment by kaylalei** [comment]
This issue was closed by #13
