### ISSUE TITLE
US1-1: Modify Database Schema to Store Status

### ISSUE THREAD

**Issue by ariel0206qyx** [CMU-313/nodebb-f24-team-kale#2]
### Description

**Add a new field in the database to store the resolved/unresolved status of each question.**
Estimated Effort: 2 hours
Dependencies: None
Milestone: Sprint 1
Acceptance Criteria: The database schema is updated, and status data can be stored and retrieved correctly.

**Comment by kaylalei** [comment]
This issue was closed by #13
